app/models/auth.py
from app.extensions import db

from flask_login import UserMixin

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(20) ,nullable=False)
    last_name = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(30), nullable=False,unique=True)
    phone_number = db.Column(db.String(15))
    password = db.Column(db.String(100), nullable=False)

app/models/post.py
from app.extensions import db

class Post(db.Model):
    id  = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120))
    content = db.Column(db.Text)

    def __repl__(self):
        return f'<Post"{self.title}">'

app/models/question.py
from app.extensions import db

class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text)
    answer = db.Column(db.Text)

    def __repr__(self):
        return f'<Question {self.content}>'

app/__init__.py
from flask import Flask

from config import Config
from app.extensions import db,bcrypt,login_manager


#Flask application factoy function
def create_app(config_class=Config):
    
    app = Flask(__name__)
    app.config.from_object(config_class)
    # Initialize flask extensions
    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    
    ##Register blueprints here
    from app.main import main as main_bp
    app.register_blueprint(main_bp)

    from app.posts import posts as posts_bp
    app.register_blueprint(posts_bp)


    from app.auth import auth as auth_pb
    app.register_blueprint(auth_pb)

    from app.questions import query as query_pb
    app.register_blueprint(query_pb)
    

    @app.route('/test/')
    def test_page():
        return '<h1>Testing the flaskApplication</h1>'
    
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)


from app.main import routes

app/main/routes.py
from app.main import main
from flask_login import login_required
from flask import render_template


@main.route('/')
def index():
    return 'This is the main blueprint'


@main.route('/dashboard')
# @login_required
def dashboard():
    return render_template('main/dashboard.html')

app/posts/__init__.py
from flask import Blueprint

posts = Blueprint('posts', __name__)


from app.posts import routes

app/posts/routes.py
from flask import render_template

from app.posts import posts 

from app.extensions import db
from app.models.post import Post

@posts.route('/posts', methods=['GET' , 'POST'])
def index():
    posts = Post.query.all()
    return render_template ('posts/index.html', posts=posts)

@posts.route('/categories')
def categories():
    return render_template('posts/categories.html')

app/questions/__init__.py
from flask import Blueprint

query = Blueprint('questions' , __name__)

from app.questions import routes

app/questions/routes.py
from flask import render_template,request,redirect,url_for
from app.models.question import Question
from app.extensions import db

from app.questions import query

@query.route('/questions', methods=('GET', 'POST'))
def index():
    questions = Question.query.all()

    if request.method == 'POST':
        new_question = Question(content=request.form['content'],
                                answer = request.form['answer'])
        db.session.add(new_question)
        db.session.commit()
        return redirect(url_for('questions.index'))

    return render_template('questions/index.html', questions=questions)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
        h2 {
            width: 100%;
        }
        .title {
            margin: 5px;
            width: 100%;
        }
        .content{
            margin: 5px;
            width: 100%;
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
        }
        .post {
            flex: 20%;
            padding: 10px;
            margin: 5px;
            background-color: #f3f3f3;
            inline-size: 100%;
        }
        .title a{
            color: #00a36f;
            text-decoration: none;
        }
        nav a {
            color: #d64161;
            font-size: 3em;
            margin-left: 50px;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <nav>
        <a href="{{ url_for('main.index')}}">FlaskApp</a>
        <a href="{{ url_for('posts.index')}}">Posts</a>
        <a href="{{ url_for('posts.categories')}}">Categories</a>
        <a href="{{ url_for('questions.index')}}">Questions</a>
        <a href="{{ url_for('auth.login')}}">Login</a>
    </nav>
    <hr>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <span class="title"><h1>{% block title %} {% endblock %}</h1></span>
    <div class="content">
        <h2>This is the main Flask blueprint</h2>
    </div>
{% endblock %}

app/templates/main/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--icon stylesheet-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/dashboard.css')}}">
</head>
<body>
    <div class="wrapper">
        <div class="sidebar">
            <!--profile image-->
            <div class="profile">
                <img src="{{url_for('static', filename='image/profile.jpg')}}" alt="">
                <h3>Eugene Nyamari</h3>
                <p>Software and Database Dev</p>
            </div>
            <!--menu item-->
            <ul>
                <li><a href="#" class="active">
                    <span class="icon"><i class="fas fa-home"></i></span>
                    <span class="item">Home</span>
                </a></li>
                <li><a href="#">
                    <span class="icon"><i class="fas fa-desktop"></i></span>
                    <span class="item">My Dashboard</span>
                </a></li>
                <li><a href="#">
                    <span class="icon"><i class="fas fa-user-friends"></i></span>
                    <span class="item">People</span>
                </a></li>
                <li><a href="#">
                    <span class="icon"><i class="fas fa-tachometer-alt"></i></span>
                    <span class="item">Performance</span>
                </a></li>
                <li><a href="#">
                    <span class="icon"><i class="fas fa-database"></i></span>
                    <span class="item">Development</span>
                </a></li>
                <li><a href="#">
                    <span class="icon"><i class="fas fa-chart-line"></i></span>
                    <span class="item">Reports</span>
                </a></li>
                <li><a href="#">
                    <span class="icon"><i class="fas fa-user-shield"></i></span>
                    <span class="item">Admin</span>
                </a></li>
                <li><a href="#">
                    <span class="icon"><i class="fas fa-cog"></i></span>
                    <span class="item">Settings</span>
                </a></li>
            </ul>
        </div>
        <!--top menu bar-->
        <div class="section">
            <div class="top_navbar">
                <div class="hamburger">
                    <a href="#"><i class="fas fa-bars"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!--Now active menu button using javascript-->
    <script>
        var hamburger = document.querySelector(".hamburger")
        hamburger.addEventListener("click", function(){
            document.querySelector("body").classList.toggle("active");
        })
    </script>
    <!-- <a href="{{ url_for('auth.logout')}}">Log out here</a> -->
</body>
</html>

app/templates/posts/categories.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} Categories {% endblock %}</h1></span>
    <div class="content">
        <h2>categoes withn posts blueprint</h2>
    </div>
{% endblock %}

app/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
    <span class="title"><h1>{% block title %}{% endblock%}</h1></span>
    <div class="content">
        <h2>this is the posts flask blueprint</h2>
        {% for post in posts %}
        <div class="post">
            <p><b>#{{ post.id }}</b></p>
            <p class="title>">
                <b>
                    <a href="#">{{ post.title}}</a>
                </b>
            </p>
            <div class="content">
                <p>{{ post.content}}</p>
            </div>
            <hr>
        </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/questions/index.html
{% extends 'base.html' %}
{% block content %}
    <span class="title"><h1>{% block title %} {% endblock %}</h1></span>
    <div class="questions">
        <h2>Question  Blueprint</h2>
        <div class="questions">
            <div class="new-questions">
                <form method="POST">
                    <p>
                        <textarea id="q-content"
                                 name="content"
                                 placeholder="Question"
                                 cols="30" rows="3"></textarea>
                    </p>
                    <textarea id="q-answer"
                                 name="answer"
                                 placeholder="Answer"
                                 cols="30" rows="3"></textarea>
                    <p><input type="submit"></p>
                </form>
            </div>
            <div class="questions-list">
                {% for question in questions %}
                    <div class="questions">
                        <h4> {{ question.content }}</h4>
                        <p>{{ question.answer }}</p>
                        <hr>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}